export const _ACTION = {
  _SET_SCH_DATE: "SetschDate",
  _SET_TAB_ACTIVE: "setTabsActive",
  _GET_SCH_DAILY: "getSchDaily",
  _GET_SCH_QR_BUNDLE: "getQrBundle",
  _GET_SCH_QR_BUNDLE_PEND: "getQrBundlePEND",
  _GET_PLANNING_BYSIZE: "getPlanningBySize",
  _GET_PLANNING_BYSIZE_PEND: "getPlanningBySizePEND",
  _GET_LIST_PART: "getListPart",
  _GET_LIST_DEFECT: "getListDefect",
  _SET_MDL_HC: "setMdlHC",
  _SET_DATA_HC: "setDataHc",
  _SET_SCHD_SELECT: "setSchdSelect",
  _SET_PLNZ_SELECT: "setplanSizeSelect",
  _SET_MDL_INPUT: "mdlInput",
  _SET_MDL_TFR: "mdlTfr",
  _SET_DEF_PAGE: "defPage",
  _SET_MULTIPLE_RTT: "multipleGood",
  _GET_QR_RESULT: "getQrResult",
  _SET_DEF_PREV: "setDefPrev",
  _GET_DEF_4_REPAIRD: "defForrepaird",
  _SET_QR_4_TFR: "setQRForTfr",
  _SET_MDL_REMARK: "setMdlRemak",
  _SET_PLAN_REMARK: "setPlanRemark",
  _GET_REP_PER_HOURLY: "getReportsQcEndHour",
  _GET_REP_DET_HOUR_DEF: "getHourDefDetail",
};
